[build]
  publish = "dist"
  command = "astro build --experimental-static-build"

[dev]
  command = "npm run dev"
  framework = "#custom"
  port = 8888
  targetPort = 3000
  autoLaunch = true

[functions]
  directory = "netlify/functions"

  